apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-user
  labels:
    app: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app 
    spec:
      containers:
      - name: user-app
        image: docker.io/temzzycode/node-user:1.0.0
        ports:
        - containerPort: 4003
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "100m"