apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello
  labels:
    app: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app 
    spec:
      containers:
      - name: hello-app
        image: docker.io/temzzycode/node-hello:1.0.0
        ports:
        - containerPort: 4000
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "100m"