apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deploy
  labels:
    app: task-app
spec:
  selector:
    matchLabels:
      app: task-app
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: task-app
    spec:
      containers:
      - name: task-app
        image: temzzycode/task:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "100m"
