apiVersion: v1
kind: Service
metadata:
  name: task-app
  labels:
    app: task-app
spec:
  type: NodePort
  selector:
    app: task-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3001
      nodePort: 32021